version: "3.8"

services:
  app:
    image: narayana3625/housing-api:latest
    container_name: housing-api
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    volumes:
      - ./logs:/app/logs
      # - ./app/mlruns:/app/mlruns
      - ./requests.db:/app/requests.db
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
